<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class IconsDataSeeder extends Seeder
{
    private $connection = 'timestamp-db';

    public function run()
    {
        DB::connection($this->connection)->table('icons')->truncate();
        DB::connection($this->connection)->table('icons')->insert($this->records());

    }

    public function records()
    {
        $records = [
            ['name' => '001.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '002.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '003.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '004.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '005.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '006.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '007.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '008.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '009.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '010.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '011.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '012.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '013.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '014.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '015.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '016.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '017.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '018.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '019.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '020.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '021.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '022.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '023.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '024.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '025.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '026.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '027.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '028.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '029.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '030.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '031.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '032.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '033.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '034.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '035.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '036.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '037.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '038.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '039.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '040.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '041.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '042.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '043.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '044.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '045.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '046.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '047.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '048.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '049.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '050.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '051.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '052.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '053.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '054.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '055.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '056.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '057.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '058.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '059.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '060.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '061.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '062.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '063.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '064.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '065.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '066.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '067.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '068.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '069.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '070.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '071.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '072.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '073.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '074.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '075.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '076.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '077.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '078.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '079.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '080.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '081.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '082.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '083.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '084.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '085.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '086.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '087.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '088.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '089.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '090.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '091.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '092.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '093.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '094.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '095.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '096.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '097.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '098.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '099.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '100.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '101.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '102.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '103.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '104.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '105.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '106.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '107.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['name' => '108.png', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ];

        return $records;
    }
}
